name: NeillMyers.com
favicon: null
layout_spectrum: 0.7290870733559132
typography_spectrum: 0.6753201470710337
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.11053315317258239
  lightness: 0.7094633774831891
  saturation: 0.9458451585378498
  rhythmicContrast: 0.37313127308152616
purpose: []
